[workspace]
resolver = "2"
members = ["token-v1", "token-v2-compatible", "token-v2-broken", "token-v2-authscope", "token-v2-noauth", "token-events-v1", "token-events-v2-swapped"]

[workspace.dependencies]
soroban-sdk = "=28.0.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
